# Simple esp demo config of a 4x4 mesh
# Each parameter is overwritten when corresponding command line value is set
#
# NOC & WIRED CONFIGURATION
#
#
# Topologies:
#   MESH
#   BUTTERFLY
#   BASELINE
#   OMEGA
#
topology: MESH
# X and Y mesh sizes
mesh_dim_x: 4
mesh_dim_y: 4
# number of flits for each router buffer
buffer_depth: 4
# size of flits, in bits
flit_size: 32
# lenght in mm of router to router connection
r2r_link_length: 1.0
# lenght in mm of router to hub connection
r2h_link_length: 2.0
n_virtual_channels: 1

# Routing algorithms:
#   XY
#   DELTA
#   WEST_FIRST
#   NORTH_LAST
#   NEGATIVE_FIRST
#   ODD_EVEN
#   DYAD
#   TABLE_BASED
# Each of the above labels should match a corresponding
# implementation in the routingAlgorithms source code directory
routing_algorithm: XY
routing_table_filename: ""

# Routing specific parameters
#   dyad_threshold: double
dyad_threshold: 0.6

# Selection Strategies:
#   RANDOM
#   BUFFER_LEVEL
#   NOP
# Each of the above labels should match a corresponding
# implementation in the selectionStrategies source code directory
selection_strategy: RANDOM

# SIMULATION PARAMETERS
#
clock_period_ps: 1000
# duration of reset signal assertion, expressed in cycles
reset_time: 1000
# overal simulation lenght, expressed in cycles
simulation_time: 100000
# collect stats after a given number of cycles
stats_warm_up_time: 1000
# power breakdown, nodes communication details
detailed: true
# stop after a given amount of load has been processed
max_volume_to_be_drained: 0
show_buffer_stats: false

# Winoc
# enable wireless, when false, all wireless channel configuration is
# ignored
use_winoc: false
# experimental power saving strategy
use_wirxsleep: false

# Verbosity level:
#   VERBOSE_OFF
#   VERBOSE_LOW
#   VERBOSE_MEDIUM
#   VERBOSE_HIGH
verbose_mode: VERBOSE_LOW

# Trace
trace_mode: false
trace_filename: ""

min_packet_size: 8
max_packet_size: 8
packet_injection_rate: 0.01
probability_of_retransmission: 0.01

# Traffic distribution:
#   TRAFFIC_RANDOM
#   TRAFFIC_TRANSPOSE1
#   TRAFFIC_TRANSPOSE2
#   TRAFFIC_HOTSPOT
#   TRAFFIC_TABLE_BASED
#   TRAFFIC_BIT_REVERSAL
#   TRAFFIC_SHUFFLE
#   TRAFFIC_BUTTERFLY
traffic_distribution: TRAFFIC_TABLE_BASED
# when traffic table based is specified, use the following
# configuration file
traffic_table_filename: "../config/exp_demo_ttable.txt"